// import java.swing.*;

// public class ABC {

// public static void main(string[] args){
//     jFrame F =new jFrame("Home");
//     jLable Hello = new JLable("Hello");
//     F.add(hello);

//     F. Setvisible(True);
//     F.Setsize( 250, 5000);
//     F.SetLayout(null);
//     F.SetDefaultcloseOperation(jFrame.EXIT_ON_CLOSE);
//     F.SetLayout(null);
//     hello.SetBounds(100,100, 50,15);


 

// }
// }




